[2021-02-02T17:09:37.449Z] + rm -rf travis-tidb.zip

[2021-02-02T17:09:37.449Z] + cp -R mybatis-3-travis-tidb/. ./

[2021-02-02T17:09:37.449Z] + rm -rf mybatis-3-travis-tidb

[2021-02-02T17:09:37.449Z] + mvn -B clean test

[2021-02-02T17:09:38.735Z] [INFO] Scanning for projects...

[2021-02-02T17:09:38.991Z] [WARNING] 

[2021-02-02T17:09:38.991Z] [WARNING] Some problems were encountered while building the effective model for org.mybatis:mybatis:jar:3.4.0-SNAPSHOT

[2021-02-02T17:09:38.991Z] [WARNING] 'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.maven.surefire:surefire-api:jar -> duplicate declaration of version 2.18.1 @ line 262, column 17

[2021-02-02T17:09:38.991Z] [WARNING] 

[2021-02-02T17:09:38.991Z] [WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.

[2021-02-02T17:09:38.991Z] [WARNING] 

[2021-02-02T17:09:38.991Z] [WARNING] For this reason, future Maven versions might no longer support building such malformed projects.

[2021-02-02T17:09:38.991Z] [WARNING] 

[2021-02-02T17:09:38.991Z] [INFO] 

[2021-02-02T17:09:38.991Z] [INFO] ------------------------------------------------------------------------

[2021-02-02T17:09:38.991Z] [INFO] Building mybatis 3.4.0-SNAPSHOT

[2021-02-02T17:09:38.991Z] [INFO] ------------------------------------------------------------------------

[2021-02-02T17:09:39.248Z] [INFO] 

[2021-02-02T17:09:39.248Z] [INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ mybatis ---

[2021-02-02T17:09:39.248Z] [INFO] 

[2021-02-02T17:09:39.248Z] [INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven) @ mybatis ---

[2021-02-02T17:09:39.505Z] [INFO] 

[2021-02-02T17:09:39.505Z] [INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-java) @ mybatis ---

[2021-02-02T17:09:39.505Z] [INFO] 

[2021-02-02T17:09:39.505Z] [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (prepare-agent) @ mybatis ---

[2021-02-02T17:09:39.762Z] [INFO] argLine set to -javaagent:/maven/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/target/jacoco.exec

[2021-02-02T17:09:39.762Z] [INFO] 

[2021-02-02T17:09:39.762Z] [INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ mybatis ---

[2021-02-02T17:09:40.019Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.

[2021-02-02T17:09:40.019Z] [INFO] Copying 2 resources to META-INF

[2021-02-02T17:09:40.019Z] [INFO] Copying 2 resources

[2021-02-02T17:09:40.019Z] [INFO] 

[2021-02-02T17:09:40.019Z] [INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ mybatis ---

[2021-02-02T17:09:40.276Z] [INFO] Compiling 350 source files to /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/target/classes

[2021-02-02T17:09:42.798Z] [INFO] /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/src/main/java/org/apache/ibatis/reflection/MetaObject.java: Some input files use unchecked or unsafe operations.

[2021-02-02T17:09:42.798Z] [INFO] /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/src/main/java/org/apache/ibatis/reflection/MetaObject.java: Recompile with -Xlint:unchecked for details.

[2021-02-02T17:09:42.798Z] [INFO] 

[2021-02-02T17:09:42.798Z] [INFO] --- license-maven-plugin:2.11:format (default) @ mybatis ---

[2021-02-02T17:09:43.054Z] [INFO] Updating license headers...

[2021-02-02T17:09:43.310Z] [INFO] 

[2021-02-02T17:09:43.310Z] [INFO] --- animal-sniffer-maven-plugin:1.14:check (check-java-1.6-compat) @ mybatis ---

[2021-02-02T17:09:43.566Z] [INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1

[2021-02-02T17:09:44.129Z] [INFO] 

[2021-02-02T17:09:44.129Z] [INFO] >>> maven-bundle-plugin:2.5.4:manifest (bundle-manifest) > process-classes @ mybatis >>>

[2021-02-02T17:09:44.129Z] [INFO] 

[2021-02-02T17:09:44.129Z] [INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-maven) @ mybatis ---

[2021-02-02T17:09:44.129Z] [INFO] 

[2021-02-02T17:09:44.129Z] [INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-java) @ mybatis ---

[2021-02-02T17:09:44.129Z] [INFO] 

[2021-02-02T17:09:44.129Z] [INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (prepare-agent) @ mybatis ---

[2021-02-02T17:09:44.129Z] [INFO] argLine set to -javaagent:/maven/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/target/jacoco.exec

[2021-02-02T17:09:44.129Z] [INFO] 

[2021-02-02T17:09:44.129Z] [INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ mybatis ---

[2021-02-02T17:09:44.129Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.

[2021-02-02T17:09:44.129Z] [INFO] Copying 2 resources to META-INF

[2021-02-02T17:09:44.129Z] [INFO] Copying 2 resources

[2021-02-02T17:09:44.129Z] [INFO] 

[2021-02-02T17:09:44.129Z] [INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ mybatis ---

[2021-02-02T17:09:44.129Z] [INFO] Compiling 51 source files to /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/target/classes

[2021-02-02T17:09:44.387Z] [INFO] 

[2021-02-02T17:09:44.387Z] [INFO] --- license-maven-plugin:2.11:format (default) @ mybatis ---

[2021-02-02T17:09:44.387Z] [INFO] Updating license headers...

[2021-02-02T17:09:44.644Z] [INFO] 

[2021-02-02T17:09:44.644Z] [INFO] --- animal-sniffer-maven-plugin:1.14:check (check-java-1.6-compat) @ mybatis ---

[2021-02-02T17:09:44.644Z] [INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1

[2021-02-02T17:09:44.899Z] [INFO] 

[2021-02-02T17:09:44.899Z] [INFO] <<< maven-bundle-plugin:2.5.4:manifest (bundle-manifest) < process-classes @ mybatis <<<

[2021-02-02T17:09:44.899Z] [INFO] 

[2021-02-02T17:09:44.899Z] [INFO] 

[2021-02-02T17:09:44.899Z] [INFO] --- maven-bundle-plugin:2.5.4:manifest (bundle-manifest) @ mybatis ---

[2021-02-02T17:09:46.266Z] [INFO] 

[2021-02-02T17:09:46.266Z] [INFO] --- maven-resources-plugin:2.7:testResources (default-testResources) @ mybatis ---

[2021-02-02T17:09:46.266Z] [INFO] Using 'UTF-8' encoding to copy filtered resources.

[2021-02-02T17:09:46.266Z] [INFO] Copying 421 resources

[2021-02-02T17:09:46.266Z] [INFO] 

[2021-02-02T17:09:46.266Z] [INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ mybatis ---

[2021-02-02T17:09:46.523Z] [INFO] Compiling 608 source files to /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/target/test-classes

[2021-02-02T17:09:48.541Z] [INFO] /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/src/test/java/org/apache/ibatis/jdbc/SelectBuilderTest.java: Some input files use or override a deprecated API.

[2021-02-02T17:09:48.541Z] [INFO] /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/src/test/java/org/apache/ibatis/jdbc/SelectBuilderTest.java: Recompile with -Xlint:deprecation for details.

[2021-02-02T17:09:48.541Z] [INFO] /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/src/test/java/org/apache/ibatis/domain/misc/RichType.java: Some input files use unchecked or unsafe operations.

[2021-02-02T17:09:48.541Z] [INFO] /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/src/test/java/org/apache/ibatis/domain/misc/RichType.java: Recompile with -Xlint:unchecked for details.

[2021-02-02T17:09:48.541Z] [INFO] 

[2021-02-02T17:09:48.541Z] [INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ mybatis ---

[2021-02-02T17:09:48.541Z] [INFO] Surefire report directory: /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/target/surefire-reports

[2021-02-02T17:09:48.541Z] [INFO] Using configured provider org.apache.maven.surefire.testng.TestNGProvider

[2021-02-02T17:09:48.541Z] 

[2021-02-02T17:09:48.541Z] -------------------------------------------------------

[2021-02-02T17:09:48.541Z]  T E S T S

[2021-02-02T17:09:48.541Z] -------------------------------------------------------

[2021-02-02T17:09:49.106Z] Running TestSuite

[2021-02-02T17:09:49.106Z] Configuring TestNG with: TestNG652Configurator

[2021-02-02T17:11:42.180Z] ERROR [main] - Error message.

[2021-02-02T17:11:42.180Z] ERROR [main] - Error with Exception.

[2021-02-02T17:11:42.180Z] java.lang.Exception: Test exception.

[2021-02-02T17:11:42.181Z] 	at org.apache.ibatis.logging.LogFactoryTest.logSomething(LogFactoryTest.java:106)

[2021-02-02T17:11:42.181Z] 	at org.apache.ibatis.logging.LogFactoryTest.shouldUseCommonsLogging(LogFactoryTest.java:39)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-02-02T17:11:42.181Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:767)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestRunner.run(TestRunner.java:617)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:254)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.run(TestNG.java:1057)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

[2021-02-02T17:11:42.181Z] Feb 03, 2021 1:11:27 AM org.apache.ibatis.logging.jdk14.Jdk14LoggingImpl warn

[2021-02-02T17:11:42.181Z] WARNING: Warning message.

[2021-02-02T17:11:42.181Z] Feb 03, 2021 1:11:27 AM org.apache.ibatis.logging.jdk14.Jdk14LoggingImpl error

[2021-02-02T17:11:42.181Z] SEVERE: Error message.

[2021-02-02T17:11:42.181Z] Feb 03, 2021 1:11:27 AM org.apache.ibatis.logging.jdk14.Jdk14LoggingImpl error

[2021-02-02T17:11:42.181Z] SEVERE: Error with Exception.

[2021-02-02T17:11:42.181Z] java.lang.Exception: Test exception.

[2021-02-02T17:11:42.181Z] 	at org.apache.ibatis.logging.LogFactoryTest.logSomething(LogFactoryTest.java:106)

[2021-02-02T17:11:42.181Z] 	at org.apache.ibatis.logging.LogFactoryTest.shouldUseJdKLogging(LogFactoryTest.java:63)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-02-02T17:11:42.181Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:767)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestRunner.run(TestRunner.java:617)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:254)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.run(TestNG.java:1057)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

[2021-02-02T17:11:42.181Z] 

[2021-02-02T17:11:42.181Z] ERROR [main] - Error message.

[2021-02-02T17:11:42.181Z] ERROR [main] - Error with Exception.

[2021-02-02T17:11:42.181Z] java.lang.Exception: Test exception.

[2021-02-02T17:11:42.181Z] 	at org.apache.ibatis.logging.LogFactoryTest.logSomething(LogFactoryTest.java:106)

[2021-02-02T17:11:42.181Z] 	at org.apache.ibatis.logging.LogFactoryTest.shouldUseLog4J(LogFactoryTest.java:47)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2021-02-02T17:11:42.181Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-02-02T17:11:42.181Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)

[2021-02-02T17:11:42.181Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:767)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestRunner.run(TestRunner.java:617)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:254)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

[2021-02-02T17:11:42.181Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)

[2021-02-02T17:11:42.181Z] 	at org.testng.TestNG.run(TestNG.java:1057)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)

[2021-02-02T17:11:42.181Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

[2021-02-02T17:11:42.182Z] ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.

[2021-02-02T17:11:42.182Z] 01:11:27.402 [main] ERROR java.lang.Object - Error message.

[2021-02-02T17:11:42.182Z] 01:11:27.404 [main] ERROR java.lang.Object - Error with Exception.

[2021-02-02T17:11:42.182Z] java.lang.Exception: Test exception.

[2021-02-02T17:11:42.182Z] 	at org.apache.ibatis.logging.LogFactoryTest.logSomething(LogFactoryTest.java:106) [test-classes/:?]

[2021-02-02T17:11:42.182Z] 	at org.apache.ibatis.logging.LogFactoryTest.shouldUseLog4J2(LogFactoryTest.java:55) [test-classes/:?]

[2021-02-02T17:11:42.182Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_222]

[2021-02-02T17:11:42.182Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_222]

[2021-02-02T17:11:42.182Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_222]

[2021-02-02T17:11:42.182Z] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_222]

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:767) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.TestRunner.run(TestRunner.java:617) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:254) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.testng.TestNG.run(TestNG.java:1057) [testng-6.8.8.jar:?]

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115) [surefire-testng-2.18.1.jar:2.18.1]

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205) [surefire-testng-2.18.1.jar:2.18.1]

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108) [surefire-testng-2.18.1.jar:2.18.1]

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111) [surefire-testng-2.18.1.jar:2.18.1]

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203) [surefire-booter-2.18.1.jar:2.18.1]

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155) [surefire-booter-2.18.1.jar:2.18.1]

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.18.1.jar:2.18.1]

[2021-02-02T17:11:42.182Z] ERROR [main] - Error message.

[2021-02-02T17:11:42.182Z] ERROR [main] - Error with Exception.

[2021-02-02T17:11:42.182Z] java.lang.Exception: Test exception.

[2021-02-02T17:11:42.182Z] 	at org.apache.ibatis.logging.LogFactoryTest.logSomething(LogFactoryTest.java:106)

[2021-02-02T17:11:42.182Z] 	at org.apache.ibatis.logging.LogFactoryTest.shouldUseSlf4j(LogFactoryTest.java:71)

[2021-02-02T17:11:42.182Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-02-02T17:11:42.182Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2021-02-02T17:11:42.182Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-02-02T17:11:42.182Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)

[2021-02-02T17:11:42.182Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:767)

[2021-02-02T17:11:42.182Z] 	at org.testng.TestRunner.run(TestRunner.java:617)

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:254)

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

[2021-02-02T17:11:42.182Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)

[2021-02-02T17:11:42.182Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)

[2021-02-02T17:11:42.182Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)

[2021-02-02T17:11:42.182Z] 	at org.testng.TestNG.run(TestNG.java:1057)

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)

[2021-02-02T17:11:42.182Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

[2021-02-02T17:11:42.182Z] Logging initialized using 'class org.apache.ibatis.logging.stdout.StdOutImpl' adapter.

[2021-02-02T17:11:42.182Z] Warning message.

[2021-02-02T17:11:42.182Z] Debug message.

[2021-02-02T17:11:42.182Z] Error message.

[2021-02-02T17:11:42.182Z] Error with Exception.

[2021-02-02T17:11:42.182Z] java.lang.Exception: Test exception.

[2021-02-02T17:11:42.182Z] 	at org.apache.ibatis.logging.LogFactoryTest.logSomething(LogFactoryTest.java:106)

[2021-02-02T17:11:42.182Z] 	at org.apache.ibatis.logging.LogFactoryTest.shouldUseStdOut(LogFactoryTest.java:79)

[2021-02-02T17:11:42.182Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2021-02-02T17:11:42.182Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2021-02-02T17:11:42.182Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2021-02-02T17:11:42.182Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)

[2021-02-02T17:11:42.182Z] 	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)

[2021-02-02T17:11:42.183Z] 	at org.testng.TestRunner.privateRun(TestRunner.java:767)

[2021-02-02T17:11:42.183Z] 	at org.testng.TestRunner.run(TestRunner.java:617)

[2021-02-02T17:11:42.183Z] 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)

[2021-02-02T17:11:42.183Z] 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)

[2021-02-02T17:11:42.183Z] 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)

[2021-02-02T17:11:42.183Z] 	at org.testng.SuiteRunner.run(SuiteRunner.java:254)

[2021-02-02T17:11:42.183Z] 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)

[2021-02-02T17:11:42.183Z] 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)

[2021-02-02T17:11:42.183Z] 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)

[2021-02-02T17:11:42.183Z] 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)

[2021-02-02T17:11:42.183Z] 	at org.testng.TestNG.run(TestNG.java:1057)

[2021-02-02T17:11:42.183Z] 	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)

[2021-02-02T17:11:42.183Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)

[2021-02-02T17:11:42.183Z] 	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)

[2021-02-02T17:11:42.183Z] 	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)

[2021-02-02T17:11:42.183Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)

[2021-02-02T17:11:42.183Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)

[2021-02-02T17:11:42.183Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

[2021-02-02T17:11:42.183Z] ==>  Preparing: select * from users where id = ? 

[2021-02-02T17:11:42.183Z] ==> Parameters: 1(Integer)

[2021-02-02T17:11:42.183Z] <==    Columns: id, name

[2021-02-02T17:11:42.183Z] <==        Row: 1, User1

[2021-02-02T17:11:42.183Z] <==      Total: 1

[2021-02-02T17:11:42.183Z] ==>  Preparing: SELECT person_id, person_name FROM person WHERE person_id = ? 

[2021-02-02T17:11:42.183Z] ==> Parameters: 1(Integer)

[2021-02-02T17:11:42.183Z] <==    Columns: PERSON_ID, PERSON_NAME

[2021-02-02T17:11:42.183Z] <==        Row: 1, John

[2021-02-02T17:11:42.183Z] <==      Total: 1

[2021-02-02T17:11:42.183Z] ==>  Preparing: SELECT person_id, person_name FROM person WHERE person_id = ? 

[2021-02-02T17:11:42.183Z] ==> Parameters: 1(Integer)

[2021-02-02T17:11:42.183Z] <==    Columns: person_id, person_name

[2021-02-02T17:11:42.183Z] <==        Row: 1, John

[2021-02-02T17:11:42.183Z] <==      Total: 1

[2021-02-02T17:11:42.183Z] Cache Hit Ratio [pet namespace]: 0.0

[2021-02-02T17:11:42.183Z] ==>  Preparing: SELECT person_id, person_name , pet_id, owner_id, pet_name FROM person, pet WHERE person_id = ? AND person_id = owner_id ORDER BY pet_id 

[2021-02-02T17:11:42.183Z] ==> Parameters: 1(Integer)

[2021-02-02T17:11:42.183Z] <==    Columns: person_id, person_name, pet_id, owner_id, pet_name

[2021-02-02T17:11:42.183Z] <==        Row: 1, John, 1, 1, Kotetsu

[2021-02-02T17:11:42.183Z] <==        Row: 1, John, 2, 1, Chien

[2021-02-02T17:11:42.183Z] <==      Total: 2

[2021-02-02T17:11:42.183Z] Cache Hit Ratio [pet namespace]: 0.0

[2021-02-02T17:11:42.183Z] ==>  Preparing: SELECT pet_id, owner_id, pet_name FROM pet WHERE pet_id = ? 

[2021-02-02T17:11:42.183Z] ==> Parameters: 1(Integer)

[2021-02-02T17:11:42.183Z] <==    Columns: pet_id, owner_id, pet_name

[2021-02-02T17:11:42.183Z] <==        Row: 1, 1, Kotetsu

[2021-02-02T17:11:42.183Z] <==      Total: 1

[2021-02-02T17:11:42.183Z] Cache Hit Ratio [pet namespace]: 0.0

[2021-02-02T17:11:42.183Z] ==>  Preparing: SELECT pet_id, owner_id, pet_name , person_id, person_name FROM pet, person where person_id = owner_id AND pet_id = ? 

[2021-02-02T17:11:42.183Z] ==> Parameters: 3(Integer)

[2021-02-02T17:11:42.183Z] <==    Columns: pet_id, owner_id, pet_name, person_id, person_name

[2021-02-02T17:11:42.183Z] <==        Row: 3, 2, Ren, 2, Rebecca

[2021-02-02T17:11:42.183Z] <==      Total: 1

[2021-02-02T17:11:42.183Z] ==>  Preparing: SELECT pet_id, owner_id, pet_name FROM pet WHERE pet_id = ? 

[2021-02-02T17:11:42.183Z] ==> Parameters: 1(Integer)

[2021-02-02T17:11:42.183Z] <==    Columns: PET_ID, OWNER_ID, PET_NAME

[2021-02-02T17:11:42.183Z] <==        Row: 1, 1, Kotetsu

[2021-02-02T17:11:42.183Z] <==      Total: 1

[2021-02-02T17:11:42.183Z] ==>  Preparing: SELECT pet_id, owner_id, pet_name FROM pet WHERE pet_id = ? 

[2021-02-02T17:11:42.183Z] ==> Parameters: 1(Integer)

[2021-02-02T17:11:42.183Z] <==    Columns: pet_id, owner_id, pet_name

[2021-02-02T17:11:42.183Z] <==        Row: 1, 1, Kotetsu

[2021-02-02T17:11:42.183Z] <==      Total: 1

[2021-02-02T17:11:42.183Z] Configuring TestNG with: TestNG652Configurator

[2021-02-02T17:11:42.183Z] Tests run: 839, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 107.951 sec <<< FAILURE! - in TestSuite

[2021-02-02T17:11:42.183Z] testNumerics(org.apache.ibatis.submitted.dynsql.DynSqlTest)  Time elapsed: 0.018 sec  <<< FAILURE!

[2021-02-02T17:11:42.183Z] org.apache.ibatis.exceptions.PersistenceException: 

[2021-02-02T17:11:42.183Z] ### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ibtest.numerics' doesn't exist

[2021-02-02T17:11:42.183Z] ### The error may exist in org/apache/ibatis/submitted/dynsql/DynSql.xml

[2021-02-02T17:11:42.183Z] ### The error may involve defaultParameterMap

[2021-02-02T17:11:42.183Z] ### The error occurred while setting parameters

[2021-02-02T17:11:42.183Z] ### SQL: select * from ibtest.numerics

[2021-02-02T17:11:42.183Z] ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ibtest.numerics' doesn't exist

[2021-02-02T17:11:42.183Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[2021-02-02T17:11:42.183Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

[2021-02-02T17:11:42.183Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[2021-02-02T17:11:42.183Z] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.Util.getInstance(Util.java:383)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1193)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:314)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:136)

[2021-02-02T17:11:42.183Z] 	at org.apache.ibatis.submitted.dynsql.DynSqlTest.testNumerics(DynSqlTest.java:127)

[2021-02-02T17:11:42.183Z] 

[2021-02-02T17:11:42.183Z] testOgnlStaticMethodCall(org.apache.ibatis.submitted.dynsql.DynSqlTest)  Time elapsed: 0.006 sec  <<< FAILURE!

[2021-02-02T17:11:42.183Z] org.apache.ibatis.exceptions.PersistenceException: 

[2021-02-02T17:11:42.183Z] ### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'description' in 'where clause'

[2021-02-02T17:11:42.183Z] ### The error may exist in org/apache/ibatis/submitted/dynsql/DynSql.xml

[2021-02-02T17:11:42.183Z] ### The error may involve org.apache.ibatis.submitted.dynsql.ognlStaticMethodCall-Inline

[2021-02-02T17:11:42.183Z] ### The error occurred while setting parameters

[2021-02-02T17:11:42.183Z] ### SQL: SELECT *     FROM ibtest.names     WHERE description LIKE 'Rock ''n Roll'     ORDER BY id

[2021-02-02T17:11:42.183Z] ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'description' in 'where clause'

[2021-02-02T17:11:42.183Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[2021-02-02T17:11:42.183Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

[2021-02-02T17:11:42.183Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[2021-02-02T17:11:42.183Z] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.Util.getInstance(Util.java:383)

[2021-02-02T17:11:42.183Z] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1193)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:314)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.submitted.dynsql.DynSqlTest.testOgnlStaticMethodCall(DynSqlTest.java:152)

[2021-02-02T17:11:42.184Z] 

[2021-02-02T17:11:42.184Z] testSelectLike(org.apache.ibatis.submitted.dynsql.DynSqlTest)  Time elapsed: 0.006 sec  <<< FAILURE!

[2021-02-02T17:11:42.184Z] org.apache.ibatis.exceptions.PersistenceException: 

[2021-02-02T17:11:42.184Z] ### Error querying database.  Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'description' in 'where clause'

[2021-02-02T17:11:42.184Z] ### The error may exist in org/apache/ibatis/submitted/dynsql/DynSql.xml

[2021-02-02T17:11:42.184Z] ### The error may involve org.apache.ibatis.submitted.dynsql.selectLike-Inline

[2021-02-02T17:11:42.184Z] ### The error occurred while setting parameters

[2021-02-02T17:11:42.184Z] ### SQL: SELECT *     FROM ibtest.names     WHERE description LIKE ?     ORDER BY id

[2021-02-02T17:11:42.184Z] ### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'description' in 'where clause'

[2021-02-02T17:11:42.184Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

[2021-02-02T17:11:42.184Z] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

[2021-02-02T17:11:42.184Z] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

[2021-02-02T17:11:42.184Z] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:400)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.Util.getInstance(Util.java:383)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:980)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3847)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3783)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2447)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2594)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2545)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1901)

[2021-02-02T17:11:42.184Z] 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1193)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:314)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141)

[2021-02-02T17:11:42.184Z] 	at org.apache.ibatis.submitted.dynsql.DynSqlTest.testSelectLike(DynSqlTest.java:112)

[2021-02-02T17:11:42.184Z] 

[2021-02-02T17:11:42.184Z] 

[2021-02-02T17:11:42.184Z] Results :

[2021-02-02T17:11:42.184Z] 

[2021-02-02T17:11:42.184Z] Failed tests: 

[2021-02-02T17:11:42.184Z]   DynSqlTest.testNumerics:127 ? Persistence 

[2021-02-02T17:11:42.184Z] ### Error querying database.  Cause...

[2021-02-02T17:11:42.184Z]   DynSqlTest.testOgnlStaticMethodCall:152 ? Persistence 

[2021-02-02T17:11:42.184Z] ### Error querying data...

[2021-02-02T17:11:42.184Z]   DynSqlTest.testSelectLike:112 ? Persistence 

[2021-02-02T17:11:42.184Z] ### Error querying database.  Cau...

[2021-02-02T17:11:42.184Z] 

[2021-02-02T17:11:42.184Z] Tests run: 839, Failures: 3, Errors: 0, Skipped: 0

[2021-02-02T17:11:42.184Z] 

[2021-02-02T17:11:42.184Z] [INFO] ------------------------------------------------------------------------

[2021-02-02T17:11:42.184Z] [INFO] BUILD FAILURE

[2021-02-02T17:11:42.184Z] [INFO] ------------------------------------------------------------------------

[2021-02-02T17:11:42.184Z] [INFO] Total time: 01:58 min

[2021-02-02T17:11:42.184Z] [INFO] Finished at: 2021-02-03T01:11:37+08:00

[2021-02-02T17:11:42.184Z] [INFO] Final Memory: 35M/750M

[2021-02-02T17:11:42.184Z] [INFO] ------------------------------------------------------------------------

[2021-02-02T17:11:42.184Z] [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (default-test) on project mybatis: There are test failures.

[2021-02-02T17:11:42.184Z] [ERROR] 

[2021-02-02T17:11:42.184Z] [ERROR] Please refer to /home/jenkins/agent/workspace/tidb_ghpr_mybatis/mybatis3/target/surefire-reports for the individual test results.

[2021-02-02T17:11:42.184Z] [ERROR] -> [Help 1]

[2021-02-02T17:11:42.184Z] [ERROR] 

[2021-02-02T17:11:42.184Z] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[2021-02-02T17:11:42.184Z] [ERROR] Re-run Maven using the -X switch to enable full debug logging.

[2021-02-02T17:11:42.184Z] [ERROR] 

[2021-02-02T17:11:42.184Z] [ERROR] For more information about the errors and possible solutions, please read the following articles:

[2021-02-02T17:11:42.184Z] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

script returned exit code 1